spring:
  datasource:
    dherokuriver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/tome"
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: govlepel@$&

server:
  port=${PORT:32500}:





